baseURL = 'https://shafu-life.win/'
relativeURLs = true
title = 'shafuブログ'
theme = 'ananke'

defaultContentLanguage = 'ja'
# defaultContentLanguageInSubdir = true
[languages]
  [languages.en]
    languageName = 'English'
    title = "shafu's blog"
    weight = 2
  [languages.ja]
    languageName = 'Japanese'
    title = 'shafuブログ'
    weight = 1
